name: app_pokedex
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3

  mobx: 2.0.7
  flutter_mobx: ^2.0.6+1
  dio: ^4.0.6
  http: ^0.13.4
  build_runner: ^2.1.11
  hive: ^2.2.3
  hive_generator: ^1.1.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.7
  modular_test: ^2.0.0
  flutter_launcher_icons: ^0.9.3

## Splash Screen


## Launcher Icon
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/pokeball-icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/icons/pokeball-icon.png

## Slidy Scripts
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  build: $runner build --delete-conflicting-outputs
  build_fvm: fvm flutter pub run build_runner build --delete-conflicting-outputs
  watch: $clean & $get & $runner watch --delete-conflicting-outputs
  build_clean: $clean & $get & $runner build --delete-conflicting-outputs
  flutter_run: flutter run --flavor debug_flavor --debug
  flutter_build_appbundle: $clean & flutter build appbundle --flavor release_flavor
  flutter_build_ios: $clean & $get & $runner build --delete-conflicting-outputs & flutter build ios
